name: phoneremote
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0+1

environment:
  sdk: ^3.13.5

dependencies:
  crypto: ^3.0.7
  cryptography: ^2.9.0
  flutter:
    sdk: flutter
  flutter_secure_storage: ^11.2.0
  http: ^1.6.0
  mobile_scanner: ^7.4.2
  multicast_dns: ^0.3.3+1
  nsd: ^5.0.1
  shared_preferences: ^2.5.5
  url_launcher: ^6.3.2
  wakelock_plus: ^1.8.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
  fonts:
    - family: Bricolage
      fonts:
        - asset: assets/fonts/bricolage_medium.ttf
          weight: 400
        - asset: assets/fonts/bricolage_medium.ttf
          weight: 500
        - asset: assets/fonts/bricolage_bold.ttf
          weight: 600
        - asset: assets/fonts/bricolage_bold.ttf
          weight: 700
